/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import framework.PostgresBackup;
import framework.ZipDirectory;
import java.io.File;
import org.apache.commons.io.FileUtils;

/**
 *
 * @author alexa
 */
public class TelaBackup extends javax.swing.JDialog {

    /**
     * Creates new form TelaBackup
     */
    public TelaBackup(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonBackupCompleto = new javax.swing.JButton();
        buttonBackupBanco = new javax.swing.JButton();
        labelStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerar Backup do Sistema");

        buttonBackupCompleto.setText("Backup Completo");
        buttonBackupCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackupCompletoActionPerformed(evt);
            }
        });

        buttonBackupBanco.setText("Backup do Banco");
        buttonBackupBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackupBancoActionPerformed(evt);
            }
        });

        labelStatus.setText("              ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelStatus)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonBackupCompleto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(buttonBackupBanco)
                        .addGap(99, 99, 99))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBackupCompleto)
                    .addComponent(buttonBackupBanco))
                .addGap(29, 29, 29)
                .addComponent(labelStatus)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackupCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackupCompletoActionPerformed
        String diretorio = "C:\\Users\\alexa\\Desktop\\backup\\app-backup";
        File file = new File(diretorio);
        
        file.mkdir();
        
        try {
            PostgresBackup.realizaBackup(diretorio);
            
            File sourceDirectory = new File("C:\\Users\\alexa\\Documents\\GitHub\\cinemax");

            FileUtils.copyDirectoryToDirectory(sourceDirectory, file);
            
            ZipDirectory.campactar(diretorio);

            FileUtils.deleteDirectory(file);
            
            labelStatus.setText("Backup gerado com sucesso!");
        } catch (Exception e) {
            labelStatus.setText("Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_buttonBackupCompletoActionPerformed

    private void buttonBackupBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackupBancoActionPerformed
        String diretorio = "C:\\Users\\alexa\\Desktop\\backup\\app-backup";
        File file = new File(diretorio);
        
        file.mkdir();
        
        try {
            PostgresBackup.realizaBackup(diretorio);

            ZipDirectory.campactar(diretorio);

            FileUtils.deleteDirectory(file);

            labelStatus.setText("Backup do banco gerado com sucesso!");
        } catch (Exception e) {
            labelStatus.setText("Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_buttonBackupBancoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaBackup dialog = new TelaBackup(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBackupBanco;
    private javax.swing.JButton buttonBackupCompleto;
    private javax.swing.JLabel labelStatus;
    // End of variables declaration//GEN-END:variables
}
