
package views;

import configuration.SpringConfig;
import entities.Cargo;
import entities.Permissao;
import java.util.Arrays;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import log.ArquivoLog;
import services.CargoService;
import services.PermissaoService;
import types.SimNaoType;
import types.TelaType;

public class TelaPermissao extends javax.swing.JDialog {
    
    private Permissao entitySearch;
    private Permissao entity;
    private List<Cargo> cargos;
    private List<TelaType> tela;
    private List<SimNaoType> permiteVisualizar;
    private List<SimNaoType> permiteCriar;
    private List<SimNaoType> permiteEditar;
    
    public TelaPermissao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
//        try{
            initComponents();

            this.setLocationRelativeTo(null);

            entitySearch = new Permissao();

            comboSearchCargos.removeAllItems();
            comboSearchCargos.addItem("");
            
            comboSearchTelas.removeAllItems();
            comboSearchTelas.addItem("");
            
            comboSearchVisualizar.removeAllItems();
            comboSearchVisualizar.addItem("");
            
            comboSearchCriar.removeAllItems();
            comboSearchCriar.addItem("");
            
            comboSearchEditar.removeAllItems();
            comboSearchEditar.addItem("");

            
            loadCargos();
                            
            for ( Cargo cargo : cargos) {
                comboSearchCargos.addItem(cargo.getNome());
            }

            for ( TelaType telaT : TelaType.values() ) {
                comboSearchTelas.addItem(telaT.getValue());
            }
            
            for ( SimNaoType simNao : SimNaoType.values() ) {
                comboSearchVisualizar.addItem(simNao.getValue());
            }
            
            for ( SimNaoType simNao : SimNaoType.values() ) {
                comboSearchCriar.addItem(simNao.getValue());
            }
            
            for ( SimNaoType simNao : SimNaoType.values() ) {
                comboSearchEditar.addItem(simNao.getValue());
            }

//        }catch(Exception e){
//            new ArquivoLog(e.toString());
            
//        }
    }
    private void loadCargos() {
        CargoService service = SpringConfig.context.getBean(CargoService.class);

        cargos = service.find();
    }
    private void load() {
        try{
            PermissaoService service = SpringConfig.context.getBean(PermissaoService.class);

            if (comboSearchCargos.getSelectedIndex() != 0) {
                entitySearch.setCargo(cargos.get(comboSearchCargos.getSelectedIndex()-1));
            }

            if (comboSearchTelas.getSelectedIndex() != 0) {
                entitySearch.setTela(Arrays.asList(TelaType.values()).get(comboSearchTelas.getSelectedIndex()-1));
            }

            if (comboSearchVisualizar.getSelectedIndex() != 0) {
                entitySearch.setPermiteVisualizar(Arrays.asList(SimNaoType.values()).get(comboSearchVisualizar.getSelectedIndex()-1));
            }

            if (comboSearchCriar.getSelectedIndex() != 0) {
                entitySearch.setPermiteCriar(Arrays.asList(SimNaoType.values()).get(comboSearchCriar.getSelectedIndex()-1));
            }

            if (comboSearchEditar.getSelectedIndex() != 0) {
                entitySearch.setPermiteEditar(Arrays.asList(SimNaoType.values()).get(comboSearchEditar.getSelectedIndex()-1));
            }

            populateTable(service.find(entitySearch));
            
            entitySearch = new Permissao();

        }catch(Exception e){
            new ArquivoLog(e.toString());
        }
    }
    
    private void populateTable(List<Permissao> list) {
        DefaultTableModel model = (DefaultTableModel) tablePermissao.getModel();
        Object rowData[] = new Object[6];
        model.setRowCount(0);
        
        for ( Permissao permissao : list ) {
            rowData[0] = permissao.getId();
            rowData[1] = permissao.getCargo().getNome();
            rowData[2] = permissao.getTela().getValue();
            rowData[3] = permissao.getPermiteCriar().getValue();
            rowData[4] = permissao.getPermiteEditar().getValue();
            rowData[5] = permissao.getPermiteVisualizar().getValue();

            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogInsert = new javax.swing.JDialog();
        buttonInsertSalvar = new javax.swing.JButton();
        comboInsertCargos = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        comboInsertTelas = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        comboInsertCriar = new javax.swing.JComboBox<>();
        comboInsertEditar = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        comboInsertVisualizar = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        dialogUpdate = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        fieldUpdateId = new javax.swing.JTextField();
        buttonUpdateSalvar = new javax.swing.JButton();
        comboUpdateTelas = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        comboUpdateCriar = new javax.swing.JComboBox<>();
        comboUpdateEditar = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        comboUpdateVisualizar = new javax.swing.JComboBox<>();
        comboUpdateCargos = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        buttonPesquisar = new javax.swing.JButton();
        buttonNovo = new javax.swing.JButton();
        comboSearchCargos = new javax.swing.JComboBox<>();
        buttonEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePermissao = new javax.swing.JTable();
        fieldSearchId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboSearchTelas = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        comboSearchCriar = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        comboSearchEditar = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        comboSearchVisualizar = new javax.swing.JComboBox<>();

        dialogInsert.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogInsert.setTitle("Cadastrar Permissão");
        dialogInsert.setModal(true);
        dialogInsert.setResizable(false);
        dialogInsert.setSize(new java.awt.Dimension(360, 270));

        buttonInsertSalvar.setText("Salvar");
        buttonInsertSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertSalvarActionPerformed(evt);
            }
        });

        comboInsertCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboInsertCargosActionPerformed(evt);
            }
        });

        jLabel15.setText("*Cargo:");

        jLabel16.setText("*Tela:");

        comboInsertTelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboInsertTelasActionPerformed(evt);
            }
        });

        jLabel17.setText("*Permite Criar:");

        comboInsertCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboInsertCriarActionPerformed(evt);
            }
        });

        comboInsertEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboInsertEditarActionPerformed(evt);
            }
        });

        jLabel18.setText("*Permite Editar:");

        comboInsertVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboInsertVisualizarActionPerformed(evt);
            }
        });

        jLabel19.setText("*Permite Visualizar:");

        javax.swing.GroupLayout dialogInsertLayout = new javax.swing.GroupLayout(dialogInsert.getContentPane());
        dialogInsert.getContentPane().setLayout(dialogInsertLayout);
        dialogInsertLayout.setHorizontalGroup(
            dialogInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogInsertLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonInsertSalvar)
                    .addGroup(dialogInsertLayout.createSequentialGroup()
                        .addGroup(dialogInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(dialogInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboInsertCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboInsertTelas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboInsertCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboInsertEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboInsertVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 46, Short.MAX_VALUE))
        );
        dialogInsertLayout.setVerticalGroup(
            dialogInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogInsertLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(dialogInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboInsertCargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboInsertTelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboInsertCriar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboInsertEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboInsertVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonInsertSalvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialogUpdate.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogUpdate.setTitle("Atualizar Permissão");
        dialogUpdate.setModal(true);
        dialogUpdate.setResizable(false);
        dialogUpdate.setSize(new java.awt.Dimension(360, 270));

        jLabel5.setText("ID:");

        fieldUpdateId.setEditable(false);

        buttonUpdateSalvar.setText("Salvar");
        buttonUpdateSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateSalvarActionPerformed(evt);
            }
        });

        comboUpdateTelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUpdateTelasActionPerformed(evt);
            }
        });

        jLabel20.setText("*Permite Criar:");

        comboUpdateCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUpdateCriarActionPerformed(evt);
            }
        });

        comboUpdateEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUpdateEditarActionPerformed(evt);
            }
        });

        jLabel21.setText("*Permite Editar:");

        comboUpdateVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUpdateVisualizarActionPerformed(evt);
            }
        });

        comboUpdateCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUpdateCargosActionPerformed(evt);
            }
        });

        jLabel22.setText("*Permite Visualizar:");

        jLabel23.setText("*Cargo:");

        jLabel24.setText("*Tela:");

        javax.swing.GroupLayout dialogUpdateLayout = new javax.swing.GroupLayout(dialogUpdate.getContentPane());
        dialogUpdate.getContentPane().setLayout(dialogUpdateLayout);
        dialogUpdateLayout.setHorizontalGroup(
            dialogUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23)
                    .addComponent(jLabel5)
                    .addComponent(buttonUpdateSalvar))
                .addGap(18, 18, 18)
                .addGroup(dialogUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboUpdateCargos, 0, 200, Short.MAX_VALUE)
                    .addComponent(comboUpdateTelas, 0, 200, Short.MAX_VALUE)
                    .addComponent(comboUpdateCriar, 0, 200, Short.MAX_VALUE)
                    .addComponent(comboUpdateEditar, 0, 200, Short.MAX_VALUE)
                    .addComponent(comboUpdateVisualizar, 0, 200, Short.MAX_VALUE)
                    .addComponent(fieldUpdateId))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        dialogUpdateLayout.setVerticalGroup(
            dialogUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogUpdateLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(dialogUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fieldUpdateId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboUpdateCargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboUpdateTelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboUpdateCriar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboUpdateEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboUpdateVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(2, 2, 2)
                .addComponent(buttonUpdateSalvar)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Permissões");

        buttonPesquisar.setText("Pesquisar");
        buttonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesquisarActionPerformed(evt);
            }
        });

        buttonNovo.setText("Novo");
        buttonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNovoActionPerformed(evt);
            }
        });

        buttonEditar.setText("Editar");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        tablePermissao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cargo", "Tela", "Cria", "Edita", "Visualiza"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePermissao.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablePermissao);
        if (tablePermissao.getColumnModel().getColumnCount() > 0) {
            tablePermissao.getColumnModel().getColumn(1).setMinWidth(150);
        }

        jLabel7.setText("Cargo:");

        jLabel8.setText("Tela:");

        jLabel11.setText("Criar:");

        jLabel13.setText("Editar:");

        jLabel14.setText("Visualizar:");

        comboSearchVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSearchVisualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboSearchTelas, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboSearchCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldSearchId, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboSearchCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboSearchEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboSearchVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEditar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboSearchCriar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboSearchEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(fieldSearchId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(comboSearchCargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboSearchTelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel14)
                            .addComponent(comboSearchVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPesquisar)
                    .addComponent(buttonNovo)
                    .addComponent(buttonEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesquisarActionPerformed
        load();
    }//GEN-LAST:event_buttonPesquisarActionPerformed

    private void buttonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNovoActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                entity = new Permissao();

                comboInsertCargos.removeAllItems();
                comboInsertCargos.addItem("");

                comboInsertTelas.removeAllItems();
                comboInsertTelas.addItem("");

                comboInsertVisualizar.removeAllItems();
                comboInsertVisualizar.addItem("");

                comboInsertCriar.removeAllItems();
                comboInsertCriar.addItem("");

                comboInsertEditar.removeAllItems();
                comboInsertEditar.addItem("");

                loadCargos();

                for ( Cargo cargo : cargos) {
                    comboInsertCargos.addItem(cargo.getNome());
                }
                for ( TelaType telaT : TelaType.values() ) {
                    comboInsertTelas.addItem(telaT.getValue());
                }

                for ( SimNaoType simNao : SimNaoType.values() ) {
                    comboInsertVisualizar.addItem(simNao.getValue());
                }

                for ( SimNaoType simNao : SimNaoType.values() ) {
                    comboInsertCriar.addItem(simNao.getValue());
                }

                for ( SimNaoType simNao : SimNaoType.values() ) {
                    comboInsertEditar.addItem(simNao.getValue());
                }

                dialogInsert.setLocationRelativeTo(null);
                dialogInsert.setVisible(true);
            }
        });
    }//GEN-LAST:event_buttonNovoActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                entity = new Permissao();
                entity.setId((Integer) tablePermissao.getValueAt(tablePermissao.getSelectedRow(), 0));
                entity = SpringConfig.context.getBean(PermissaoService.class).find(entity).get(0);

                fieldUpdateId.setText(String.valueOf(entity.getId()));

                loadCargos();
                comboUpdateCargos.removeAllItems();

                int count = 0;
                for ( Cargo cargo: cargos ) {
                    comboUpdateCargos.addItem(cargo.getNome());
                    if ( cargo.getId().equals(entity.getCargo().getId()) ) {
                        comboUpdateCargos.setSelectedIndex(count);
                    }
                    count++;
                }
//                for ( Cargo cargo : cargos) {
//                    comboUpdateCargos.addItem(cargo.getNome());
//                }
//                comboUpdateCargos.setSelectedIndex(cargos.indexOf(entity.getCargo()));

                comboUpdateTelas.removeAllItems();
                for ( TelaType telaT: TelaType.values() ) {
                    comboUpdateTelas.addItem(telaT.getValue());
                }
                comboUpdateTelas.setSelectedIndex(Arrays.asList(TelaType.values()).indexOf(entity.getTela()));

                comboUpdateVisualizar.removeAllItems();
                for ( SimNaoType simNao : SimNaoType.values() ) {
                    comboUpdateVisualizar.addItem(simNao.getValue());
                }
                comboUpdateVisualizar.setSelectedIndex(Arrays.asList(SimNaoType.values()).indexOf(entity.getPermiteVisualizar()));

                comboUpdateCriar.removeAllItems();
                for ( SimNaoType simNao : SimNaoType.values() ) {
                    comboUpdateCriar.addItem(simNao.getValue());
                }
                comboUpdateCriar.setSelectedIndex(Arrays.asList(SimNaoType.values()).indexOf(entity.getPermiteCriar()));

                comboUpdateEditar.removeAllItems();
                for ( SimNaoType simNao : SimNaoType.values() ) {
                    comboUpdateEditar.addItem(simNao.getValue());
                }
                comboUpdateEditar.setSelectedIndex(Arrays.asList(SimNaoType.values()).indexOf(entity.getPermiteEditar()));

                dialogUpdate.setLocationRelativeTo(null);
                dialogUpdate.setVisible(true);
            }
        });
    }//GEN-LAST:event_buttonEditarActionPerformed

    private void buttonInsertSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertSalvarActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                entity.setCargo(cargos.get(comboInsertCargos.getSelectedIndex() -1));
                entity.setTela(Arrays.asList(TelaType.values()).get(comboInsertTelas.getSelectedIndex() -1));
                entity.setPermiteEditar(Arrays.asList(SimNaoType.values()).get(comboInsertEditar.getSelectedIndex() -1));
                entity.setPermiteVisualizar(Arrays.asList(SimNaoType.values()).get(comboInsertVisualizar.getSelectedIndex() -1));
                entity.setPermiteCriar(Arrays.asList(SimNaoType.values()).get(comboInsertCriar.getSelectedIndex() -1));

                PermissaoService service = SpringConfig.context.getBean(PermissaoService.class);

                service.insert(entity);
                dialogInsert.dispose();
                load();
            }
        });
    }//GEN-LAST:event_buttonInsertSalvarActionPerformed

    private void buttonUpdateSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateSalvarActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                entity.setCargo(cargos.get(comboUpdateCargos.getSelectedIndex()));
                entity.setTela(Arrays.asList(TelaType.values()).get(comboUpdateTelas.getSelectedIndex()));
                entity.setPermiteEditar(Arrays.asList(SimNaoType.values()).get(comboUpdateEditar.getSelectedIndex()));
                entity.setPermiteVisualizar(Arrays.asList(SimNaoType.values()).get(comboUpdateVisualizar.getSelectedIndex()));
                entity.setPermiteCriar(Arrays.asList(SimNaoType.values()).get(comboUpdateCriar.getSelectedIndex()));

                PermissaoService service = SpringConfig.context.getBean(PermissaoService.class);

                service.update(entity);
                dialogUpdate.dispose();
                load();
            }
        });
    }//GEN-LAST:event_buttonUpdateSalvarActionPerformed

    private void comboSearchVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSearchVisualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSearchVisualizarActionPerformed

    private void comboInsertCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboInsertCargosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboInsertCargosActionPerformed

    private void comboInsertTelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboInsertTelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboInsertTelasActionPerformed

    private void comboInsertCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboInsertCriarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboInsertCriarActionPerformed

    private void comboInsertEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboInsertEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboInsertEditarActionPerformed

    private void comboInsertVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboInsertVisualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboInsertVisualizarActionPerformed

    private void comboUpdateTelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUpdateTelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboUpdateTelasActionPerformed

    private void comboUpdateCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUpdateCriarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboUpdateCriarActionPerformed

    private void comboUpdateEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUpdateEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboUpdateEditarActionPerformed

    private void comboUpdateVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUpdateVisualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboUpdateVisualizarActionPerformed

    private void comboUpdateCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUpdateCargosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboUpdateCargosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPermissao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPermissao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPermissao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPermissao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaPermissao dialog = new TelaPermissao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonInsertSalvar;
    private javax.swing.JButton buttonNovo;
    private javax.swing.JButton buttonPesquisar;
    private javax.swing.JButton buttonUpdateSalvar;
    private javax.swing.JComboBox<String> comboInsertCargos;
    private javax.swing.JComboBox<String> comboInsertCriar;
    private javax.swing.JComboBox<String> comboInsertEditar;
    private javax.swing.JComboBox<String> comboInsertTelas;
    private javax.swing.JComboBox<String> comboInsertVisualizar;
    private javax.swing.JComboBox<String> comboSearchCargos;
    private javax.swing.JComboBox<String> comboSearchCriar;
    private javax.swing.JComboBox<String> comboSearchEditar;
    private javax.swing.JComboBox<String> comboSearchTelas;
    private javax.swing.JComboBox<String> comboSearchVisualizar;
    private javax.swing.JComboBox<String> comboUpdateCargos;
    private javax.swing.JComboBox<String> comboUpdateCriar;
    private javax.swing.JComboBox<String> comboUpdateEditar;
    private javax.swing.JComboBox<String> comboUpdateTelas;
    private javax.swing.JComboBox<String> comboUpdateVisualizar;
    private javax.swing.JDialog dialogInsert;
    private javax.swing.JDialog dialogUpdate;
    private javax.swing.JTextField fieldSearchId;
    private javax.swing.JTextField fieldUpdateId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePermissao;
    // End of variables declaration//GEN-END:variables
}
